install:
- ps: Install-Product node 8.11.4 x64
configuration:
Release
platform:
Any CPU
test: 'off'
deploy: 'off'
before_build:
- cmd: set ASPNETCORE_ENVIRONMENT=Production
os: Visual Studio 2017
image: Visual Studio 2017